<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ExplorationManager.cs" />
    <Compile Remove="IndymonUtilities.cs" />
    <Compile Remove="TournamentManager.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gameplay\Gameplay.csproj" />
    <ProjectReference Include="..\GameSimulator\GameSimulator.csproj" />
  </ItemGroup>

</Project>
